### ISSUE TITLE
KDE support

### ISSUE THREAD

**Issue by Maxiride** [nana-4/materia-theme#143]
I really like this theme and I would *love* to see it on my KDE based distro.

Are there plans to do a KDE version? Is it feasible?

**Comment by nana-4** [comment]
> Is it feasible?

Yap. But to be honest, I'm not an active user of KDE. Also I have many tasks ([these](https://github.com/nana-4/Flat-Plat#planned-features) and others) to do. Therefore, even if we support KDE, it may be quite later. :)

**Comment by OriginalFannibal** [comment]
The Papirus Development Team recently launched their port of [Adapta for KDE](https://github.com/PapirusDevelopmentTeam/adapta-kde). Isn't Adapta based off Materia? Might this be of some help in this issue then?

**Comment by nana-4** [comment]
Yes, Adapta should be based on Materia (ex-Flat-Plat). I might refer to it when supporting KDE.

**Comment by Warmuser** [comment]
I would like to support these and other themes. But I don't know how to create from the beginning to ending themes for GNOME/KDE5. Softwares, Guides, Video tutorials? I think they are really important but I didn't find nothing of useful on Youtube. Anyway I learned by myself HTML5, CSS3 and Javascript languages for the web develpoment. Can you suggest me what to use to edit themes and important guides? Maybe I can help you in the future. Sorry for the off topic but I'm really interested to support these and other projects. And I think maybe also other users share the same interest. :)

**Comment by nana-4** [comment]
@Warmuser 
I appreciate you are trying to help to this project. :)

As you say, it is quite difficult to find theme guides unfortunately. In my experience, I think the best guide is **the upstream code of the theme**. Its commit history and comments would also be helpful.

For GNOME/GTK+, I linked the upstream Adwaita code to [`HACKING.md#upstream-theme-sources`](https://github.com/nana-4/materia-theme/blob/master/HACKING.md#upstream-theme-sources).

In order to address each GTK3 app and gnome-shell extension, it is good to look for `.css` file on each repository. Please note that some are hard-coded and some are not.

For GTK3, `gtk3-widget-factory`, `gtk3-demo` and the [GTK+ Inspector](https://blog.gtk.org/2017/04/05/the-gtk-inspector/) are also **VERY** useful.

This official document would also help you: https://developer.gnome.org/gtk3/stable/theming.html

---

In the case of KDE, I found the good official documentation:
- https://techbase.kde.org/Development/Tutorials/Plasma4/Theme
- https://techbase.kde.org/Development/Tutorials/Plasma4/ThemeDetails
- https://techbase.kde.org/Development/Tutorials/Plasma5/ThemeDetails

**Comment by Warmuser** [comment]
@nana-4 thank you so much!!! :)

**Comment by ArchangeGabriel** [comment]
@varlesh Would you add a Materia KDE theme alongside your existing Adapta/Arc ones? That would be wonderful.

**Comment by varlesh** [comment]
@ArchangeGabriel Full support impossible. Because kvantum engine not support buttons animation and other effects. It's will be looking as GTK2-version and Adapta KDE

**Comment by ArchangeGabriel** [comment]
@varlesh Having a matching static theme would already be awesome! I don’t like Adapta color scheme, so a Materia KDE theme would be better for me. ;)

**Comment by varlesh** [comment]
in progress:
![image](https://user-images.githubusercontent.com/8083855/38356195-20c7fa34-38d0-11e8-9015-605ea071349f.png)

**Comment by ArchangeGabriel** [comment]
Nice, I know my future theme. :+1:

**Comment by nana-4** [comment]
@varlesh Looks sooo good! Thank you :heart: 

Also thank you @ArchangeGabriel for your suggestion. :)

**Comment by varlesh** [comment]
@nana-4 Thx :) I'm little change icons and fonts colors for better compatibility with Papirus icons....
Materia example:
![image](https://user-images.githubusercontent.com/8083855/38751074-052cbc30-3f68-11e8-8f2d-beb757afc792.png)

**Comment by actionless** [comment]
looks really nice!
are you also going to test its compatibility with the `./change_color.sh` script?

**Comment by varlesh** [comment]
@actionless It's impossible, because used different standarts for colors. 
For example,
-  plasma theme use HEX - `#ffffff`
- color-scheme use RGB - `255, 255, 255`
- yakuake use PNG - it's raster graphics

**Comment by actionless** [comment]
so, in plasma it's already possible

rgb can be solved with adding a similar function to change_color.sh: https://github.com/themix-project/oomoxify/blob/master/scripts/hex_to_rgba.sh

png can be solved by using SVG template and rendering it with script: https://github.com/nana-4/materia-theme/blob/master/src/gtk/render-assets.sh, however, i am not sure if single application is worth it

**Comment by varlesh** [comment]
It's hard for unification... and why this really needed? I'm make theme for KDE/Qt-apps with GTK-Theme unification. I think, it's enought.
Nevertheless, sources available and you can fork it and modify what you want:
https://github.com/PapirusDevelopmentTeam/materia-kde

**Comment by actionless** [comment]
> and why this really needed?
for accessibility

i do not use kde so i don't have any personal interest, but i was just suggesting what for people who use it it will be nice to have that feature available the same as it available in materia's gnome-shell, cinnamon, metacity and other themes

**Comment by carlos22** [comment]
I really hate that ALL newer themes use blue as their highlight color. Especially if you use your computer at late times of the day this is really bad as it keeps you awake. I prefer the ubuntu style orange/red colors and love oomox for giving me the option to change the colors of the theme :-)

**Comment by nana-4** [comment]
I've just mentioned [PapirusDevelopmentTeam/materia-kde](https://github.com/PapirusDevelopmentTeam/materia-kde) in the `README.md` with 614d27b588f5accfc193706c610772ef09b6a2a0.
(Sorry for being late.)

Since I don't have much time and it's beyond my capacity (I'm not a KDE user, btw), I will leave it to @PapirusDevelopmentTeam and would like to close this issue.

Thanks again @varlesh and @PapirusDevelopmentTeam :D
