### ISSUE TITLE
OLED Black version :)

### ISSUE THREAD

**Issue by bresilla** [nana-4/materia-theme#160]
Hi, firstly, great work man. I think that this is the best material theme for GTK apps.

I have recently switched to an OLED laptop, and I am using United theme because of the blacks,
but I would love to have your theme as pure black.

I saw that you can compile it with sass to whatever color. Do you see the possibility to make a pure black version anytime soon??

Thanks and keep the good work.
Appreciated a lot:100:

**Comment by actionless** [comment]
you can edit the colors with this app:
https://github.com/actionless/oomox

**Comment by nana-4** [comment]
I'm sorry but I don't want to increase theme variants any more.

I think _a pure black version_ will not go well. Because Materia uses **black** shadows as borders for many widgets (e.g. button, entry, etc.), if the theme has pure black backgrounds it wolud be hard to see the boundaries. That's not good for UI/UX.

Exactly there is a great tool **oomox** that can change the color scheme. Please try to use oomox, or you can fork and change the color scheme directly.
