### ISSUE TITLE
Transparent top bar and restyling the dock

### ISSUE THREAD

**Issue by lokesh-krishna** [nana-4/materia-theme#169]
This is an enhancement request. I absolutely love your adherence to Material Design guidelines and they help create a rather unified experience with my Android phone. One thing I noticed and really appreciate is that you nail the colors of the top bar and window controls, creating the kind of contrast with maximized windows that all well-designed Material Design apps do.

However, in the normal home screen of Android, the status bar is always kept fully transparent, with a slightly dark overlay in case of a light wallpaper. Presently, the top bar is semi-transparent when using GNOME 3.26 and transparent elements are something Material Design avoids. 

I am not sure if the dark overlay in case of light wallpapers can be implemented but it would be really nice to have a fully transparent top bar, especially when it can be dynamically made opaque in GNOME 3.26 and above. That would offer an even more complete Material Design experience. While I don't know where this is specified in Material Design guidelines, this is how Google has been doing it ever since the launch of Android Lollipop with Material Design, back in 2014.

It would be nice to see this change also reflected in the theming for Dash to Dock if it is something you can do. The dock in Android has either been fully transparent (Google Now Launcher and Pixel Launcher in Pixel 2) or had a frosted transparent background (Pixel Launcher in Pixel). Personally, I think that a frosted background would look great.

**Comment by nana-4** [comment]
Sorry but I don't think this will go well. The design of transparent or slightly dark overlay top bar is not bad. However, with GNOME desktop, it has some problems.

We _always_ need **enough contrast**, even if wallpaper is bright or complex.
Compared with Android, the desktop screen is **wide**, so we'll easily lose sight of the panel buttons if the contrast is weak.

Also, I personally use Dash to Dock with panel mode enabled. If we change the top bar to transparent, it 
would look bad when combined with extended Dash to Dock. This is another reason why I'm not positive about your proposal.

_Here is an example of the top bar which has slightly dark overlay with complex wallpaper and extended Dash to Dock:_
![image](https://user-images.githubusercontent.com/9556384/32078613-7dffc252-bae2-11e7-9d8f-248b957110f4.png)

> transparent elements are something Material Design avoids.

I don't think so. In Material Design guidelines, there are a lot of translucent elements. For example:
https://material.io/guidelines/style/imagery.html
https://material.io/guidelines/layout/structure.html#structure-system-bars

> I am not sure if the dark overlay in case of light wallpapers can be implemented

AFAIK, gnome-shell doesn't have such a feature (for now). 😕 

> It would be nice to see this change also reflected in the theming for Dash to Dock if it is something you can do.

AFAIK, Ubuntu Dock (a fork of Dash to Dock) has dynamic transparency (as well as GNOME Shell 3.26), but the upstream Dash to Dock has not implemented it yet.

BTW, I'm not trying to make Materia look like Android. Because things going well with the _mobile interface_ will not always go well with the _desktop interface_.

**Comment by lokesh-krishna** [comment]
> Also, I personally use Dash to Dock with panel mode enabled. If we change the top bar to transparent, it would look bad when combined with extended Dash to Dock. This is another reason why I'm not positive about your proposal.

Actually, Ubuntu Dock isn't really a fork of Dash to Dock but is based off a branch of it. All the features  are present in Dash to Dock as well and you can check them out yourself if you download the latest GitHub version. Here is what the dock and panel look like with adaptive transparency:

![dock-dynamic-transparency](https://user-images.githubusercontent.com/20235646/32083045-70d10b7c-badd-11e7-9121-4da0d9a928d8.png)

> I don't think so. In Material Design guidelines, there are a lot of translucent elements.

Hmmm... True.


> BTW, I'm not trying to make Materia look like Android. Because things going well with the mobile interface will not always go well with the desktop interface.

Completely agree! Shall I close this issue then?

**Comment by nana-4** [comment]
OK! So, I'd like to close this issue. :)
