### ISSUE TITLE
Accent color 

### ISSUE THREAD

**Issue by sevachka** [nana-4/materia-theme#19]
Hey, I have just installed the newest master. Do you like the accent color in the Gnome-Shell (some pinkish)? :) I thought the blue one was nicer to the eye.

What do the others think?

P.S. The radiant color in the gdm-wallpaper doesn´t work nice with my laptop and pc screen (Dell u2515). They appear as rings and not like a smooth gradient.

**Comment by nana-4** [comment]
Yes, I like the new accent color personally.
The pink color is used for **accents** in many Material Design samples, and it looks good with various **primary color**, imo. Try this. https://www.getmdl.io/customize/index.html

Therefore, I'm not going to change the color at the moment.

P.S. I'll reconsider about the problem of GDM wallpaper... Thanks for your bug report.

**Comment by sevachka** [comment]
Maybe I need to get used to it. :)

**Comment by IShashkin** [comment]
I like old colors scheme more than new. It is very toxic for eyes now. imho

**Comment by sevachka** [comment]
well, you get used to it. I like it fance. But this one is maybe a little too much. :) The blue (turquoise) accent color does fit very good. Maybe it should be also used in the shell?

**Comment by nunodio** [comment]
@IShashkin i agree with you. The old colors i guess were perfect.

**Comment by fayad** [comment]
Old color scheme was perfect and gave an identity. Specially the gtk color which suited assets well. I switched to old version after a pull.

**Comment by sevachka** [comment]
@fayad but I have to say I didn´t like the green progress bar. The new one fits in that matter better. :)

**Comment by nana-4** [comment]
Sorry for my late reply.
Well, I've tried a variety of color schemes (including "teal" and "deep-orange"), which also did not match for me.
I'll change it if there is something better color scheme, but I don't want to return to the old color scheme because [Flat UI Colors](https://flatuicolors.com/) is not [Material Design color palette](https://www.google.com/design/spec/style/color.html#color-color-palette). :sweat_smile:

**Comment by lokesh-krishna** [comment]
I think [indigo](https://www.materialpalette.com/blue-grey/indigo) goes really well with blue grey.

**Comment by actionless** [comment]
also now you can use change_color.sh script inside Materia or just use the oomox app to adjust the accent color

**Comment by DarthWound** [comment]
Hello, by the way some instructions in readme about change_color.sh would be welcomed.

**Comment by nana-4** [comment]
@DarthWound Indeed. It would be more appropriate to write in `HACKING.md` than `README.md`. I'ill write about the `change_color.sh` script.

**Comment by DarthWound** [comment]
Thank you :)

By the way, I see you on several forums/websites, and it looks like that when some people talk about a fork of Materia, it's kinda "hurting" you. Be proud because behind every Materia fork it's YOUR work that is promoted/congratulated. Yesterday I talked about Equilux on Reddit but I know that without Materia there won't be any Equilux and I credited Materia in a comment :D We love what you've done so far don't worry about that, keep up the good work because Materia is one of the best themes and without a doubt the best base for others.

**Comment by nana-4** [comment]
I wrote about the script with caa354b2177673fe5bddfe586c8f7707477b87c1. (Sorry for being late.)

@DarthWound 
Thank you for your kind words and thoughtfulness. :)

Unfortunately, some influential websites introduce folk themes without mentioning it's a derivative of Materia. Not only that, they often tell Materia's ideas as if they were ideas from the fork theme itself. So, that's a shame but this theme may not be well-known to people.

**Comment by DarthWound** [comment]
Yeah I know, I often see that myself. Look at how medias talk about Ubuntu without mentioning Debian 4/5 times :D But that's how they work. I won't mention any website specifically because I'm not here to start a war or a rant, but vast majority of them is just "talk about this popular thing to make some clicks without searching further", even the most popular and most appreciated ones. I'm usually quite disappointed when I'm looking for news around GNU/Linux, and that's everyday. Sometimes we discover nice stuff, but let's face it the best comes from community itself (Reddit, forums...).

Thanks for the script instructions in `HACKING.md`.

**Comment by actionless** [comment]
and that's even without mentioning medias which are referencing to `GNU+Linux` as just `Linux` :smiley:

**Comment by nana-4** [comment]
The big difference from Debian/Ubuntu is that Materia (or Flat-Plat) is not mentioned even 1/5 times. Everyone knows that Ubuntu is based on Debian, but Materia and its forks are not. I often see such wording:

> Flat-Plat is very similar to Adapta.
> Flat-Plat looks like Adapta.
> Adapta has compact variant for low-resolution. That's a good idea.

When I see such words, I feel pretty complicated. It sounds like Flat-Plat mimicked Adapta. I think such a misunderstanding is what the media induced. Until recently I ignored it, but as I thought that misunderstanding will spread more and more as I leave it out, I started protesting against such a media that is the primary cause. 😃

**Comment by nana-4** [comment]
Okay, in `v20180321`, this theme got a big color scheme change and changed the accent color from **Pink A200** `#FF4081` to **Teal 500** `#009688` (thanks to your opinions). _Now the color scheme is much close to the original one!_

I think this issue is now outdated, so I opened new issue and would like to close this. If you have any opinions about (new) color scheme, please put it here: #220 

Thank you all for your valuable suggestion. :smile:
