### ISSUE TITLE
Minimize, maximize and close buttons are black

### ISSUE THREAD

**Issue by chuutatsu** [nana-4/materia-theme#198]
- Materia version: 3.26.20171213 (installed from AUR)
- GTK+ 3: 3.22
- Distribution: Manjaro
- Desktop environment: Mate 1.18
- Steps to reproduce: Install the latest Materia theme from AUR and apply the theme
- Problem:
In Materia normal theme (not light version), the three buttons on the right of the titlebar: minimize, maximize and close button are used to be white. After the latest update from AUR, those three buttons turned black and a little hard to be seen and noticed.

In Materia & Materia Dark (they were used to be white in the previous version of Materia):
![screenshot at 2018-01-17 18-14-49](https://user-images.githubusercontent.com/24815847/35040086-7cc771f8-fbb2-11e7-96a9-b57883dc249e.png)

In Materia Light (this was alright since they were on grey background title bar):
![screenshot at 2018-01-17 18-15-31](https://user-images.githubusercontent.com/24815847/35040132-9ee2cd8c-fbb2-11e7-822d-fad4641f98a2.png)

Please fix this!

**Comment by AlexWayfer** [comment]
I think it's related to #195.

`librsvg` 2.42.1 with fix doesn't released yet.

And in AUR not the latest version of `materia-theme` with work-around for it (flagged as out of date).

**Comment by nana-4** [comment]
Hi, thank you for the report. :)

This bug has already been fixed with 6fe2f0771003a6e4c78b10b962d96d954158d657.
However, as @AlexWayfer mentioned, it seems the AUR package has not been updated yet. (Its maintainer is @cthbleachbit, not me.)

Please wait for the package update, or you can also manually install this theme following the [README](https://github.com/nana-4/materia-theme#manual-installation).

**Comment by chuutatsu** [comment]
Okay, thanks for the fast responses!

I'll try to reinstall manually then.
