### ISSUE TITLE
Materia theme installation failed

### ISSUE THREAD

**Issue by ppisarcik** [nana-4/materia-theme#208]
**NOTE: Before reporting a bug, please check whether it also occurs with other themes.**
> If the bug also occurs with other themes (especially upstream default theme),
it is very likely an upstream issue.
Hello I cannot install materia theme I added dependency repository then sudo apt update and then sudo apt install materia-theme and I got this "materia-theme : Depends: libgtk-3-common (>= 3.22.15) but 3.18.9-1ubuntu3.3 is to be installed"

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

If you report a bug or ask a question, please include the following information as required:
- Materia version
- GTK+ 3 version (You can check it with `pkg-config --modversion gtk+-3.0`)
- Distribution (and version)
- Desktop environment (and version)
- Related application (and version)
- Steps to reproduce
- Screenshot(s)

**Comment by nana-4** [comment]
Hi @ppisarcik, thanks for your report! I confirmed this issue with **Ubuntu 16.04**.

@igor-dyatlov, could you please remove the version restriction of `libgtk-3-common`? (`>= 3.22.15`)
Although Materia supports GTK+ `>=3.18`, I think it's okay just to remove the version restriction.

**Comment by USBA** [comment]
This comment is not about this issue. 

Hey @nana-4 ,
I need a help.
I'm trying to make a gtk and shell theme to look like this macOS concept design
![bckx8714gs](https://user-images.githubusercontent.com/19838220/36944259-6dd6e734-1fbe-11e8-8580-971b81a52fb9.png)

So I need to curve the edges of the background of places sidebar of Nautilus.
I tried using "first-child" and "last-child". but it's not working.  
(please check the 2989th line in the "gtk.css")
![screenshot from 2018-03-04 01-08-02 fdfs](https://user-images.githubusercontent.com/19838220/36944325-c5d50d84-1fbf-11e8-9d04-e0258461a834.png)

I need to curve all these edges 
![screenshot from 2018-03-04 01-08-02 fdfs_li](https://user-images.githubusercontent.com/19838220/36944334-e27b86d4-1fbf-11e8-887f-d0fde9810497.jpg)

Here's my unfinished theme.
[macOS11.zip](https://github.com/nana-4/materia-theme/files/1778346/macOS11.zip)
If you can, please help me. 

I'm really sorry for asking your help in GitHub. Because I don't know any other way to contact you.
Thanks.






>

**Comment by ppisarcik** [comment]
Thank you I removed version restriction and it's working

**Comment by igor-dyatlov** [comment]
@nana-4 fixed the problem. Updated the repository.

**Comment by nana-4** [comment]
@ppisarcik You're welcome :)

@igor-dyatlov Great! Thanks a lot! 🎉

**Comment by nana-4** [comment]
@USBA It's okay to ask for help, but _this_ is not an appropriate place (as you know).

How about opening an issue in your [ASHES-theme](https://github.com/USBA/ASHES-theme/issues) repository and talk together there? Or, the best practice I think is to create your new theme repository, open the issue, and tag me (@nana-4). Then I get notifications and I may help you if I can. :)
