### ISSUE TITLE
update leftover hardcoded colors in the scss template to be template values

### ISSUE THREAD

**Issue by actionless** [nana-4/materia-theme#216]
hi, in your latest fix you've added to the template tooltip with color `$grey_800`

however in that template there are couple of more hardcoded color values, you can assign this issue to me (i am a bit busy right now, so creating ticket not to forget about it)

**Comment by nana-4** [comment]
Hi, thanks for the ticket and PR!

I intentionally hard-coded `$tooltip_bg_color` because if both `%MENU_BG%` and `%SEL_FG%` are defined with blighter colors, tooltip's text color will be almost invisible. But I decided to merge your PR and add `$tooltip_fg_color: %MENU_FG%;` to deal with it.

Thanks again for your work!
