### ISSUE TITLE
Vertical padding in Nautilus

### ISSUE THREAD

**Issue by hfel** [nana-4/materia-theme#236]
Hi! It would be nice if the elements in the sidebar of Nautilus had more vertical padding in order to avoid the quite inelegant patch of unused space:
![Materia](https://user-images.githubusercontent.com/16854594/38593246-b5203664-3d40-11e8-9dd5-819aa3133050.png)
Compare with the Numix theme:
![Numix](https://i.imgur.com/IwdfB4f.png)

**edit:**

I have a HiDPI screen, perhaps the issue is with the icons not scaling together with the text on HiDPI screens? I didn't have the same problem with Adapta though.

**Comment by nana-4** [comment]
Hi, thanks for your report.

Hm, it looks very strange. I couldn't reproduce it in my environment.

Does this problem also occur in **Adwaita**? Or, does it also occur with **other icon themes**?

**Comment by hfel** [comment]
In fact, this doesn't seem to be confined to Nautilus alone; items in the GNOME menus have different padding as well:

**Materia:**
![captura de pantalla de 2018-04-13 11-03-28](https://user-images.githubusercontent.com/16854594/38726474-8b4688d6-3f0a-11e8-939f-2cb3805dfe3e.png)

**Adapta:**
![captura de pantalla de 2018-04-13 11-03-36](https://user-images.githubusercontent.com/16854594/38726476-8e0ec150-3f0a-11e8-8e66-ca01b2db870c.png)

**Comment by nana-4** [comment]
> I have a HiDPI screen, perhaps the issue is with the icons not scaling together with the text on HiDPI screens? I didn't have the same problem with Adapta though.

From your screenshots, icons don't seem to be scaled together even in Adwaita and Adapta. 

> As you can see, Adwaita seems to have more padding.

Compared to the screenshot of Numix, Adwaita's one looks rather similar to Materia. FYI, Adwaita's rows height in the sidebar is `36px`, and Materia's one is `32px` in normal scaling.

> Adapta:

I don't think Adapta can be comparable because it's not upstream and it's sizing in a quite _quirky_ way (using `em` instead of `px`). So please use the upstream **Adwaita** for comparison. :)

Anyway, to me it looks like an upstream GTK+ issue. Could you report this issue to the upstream?

**Comment by hfel** [comment]
Sure, though I'm not an expert, so not exactly sure where I should report it; to Adwaita or GTK+? 

Are Materia's rows' heights somehow dependent on Adwaita's rows' heights?

**Comment by hfel** [comment]
Bump :)

Just wondering if there's been any progress on this.

**Comment by nana-4** [comment]
@hfel So sorry for the late reply. I was pretty busy for other things... Also I was thinking that it's bad timing to report a issue since upstream GNOME was just transitioning from Bugzilla to Gitlab. :)

> Sure, though I'm not an expert, so not exactly sure where I should report it; to Adwaita or GTK+?

[GTK3 Adwaita](https://gitlab.gnome.org/GNOME/gtk/tree/master/gtk/theme/Adwaita) is part of GTK+, so it's okay to report it to [GTK+](https://gitlab.gnome.org/GNOME/gtk).

By the way, from your screenshots, its scale factor doesn't look like exactly 200%. Perhaps aren't you enabling the _experimental fractional scaling_?

![image](https://user-images.githubusercontent.com/9556384/40883060-98f84670-672f-11e8-81ed-22c25ea607be.png)

I think you'll need such exact information when reporting the issue to the upstream.

**Comment by hfel** [comment]
No worries and thanks for the thorough reply, I'll try to report it upstream! :)
