### ISSUE TITLE
Drop support wishlist

### ISSUE THREAD

**Issue by nana-4** [nana-4/materia-theme#258]
... for less maintenance burden. These are basically old and troublesome to maintain:

Component | Description
--- | ---
GTK+ `3.18` | It's too old, not easy to control the sizes, and has very different APIs than the stable `3.22`. In Materia, it's no longer actively supported. **UPDATE:** Done.
GTK+ `3.20` | It's a bit obsolete. GTK3 is now stable with `3.22`. Most major distros with the latest version (including stability-oriented distros, e.g. Debian, RHEL, Ubuntu LTS) are now using GTK+ `3.22`.x. **UPDATE:** Done.
Budgie `<=10.3.x` | It's obsolete nowadays. I suppose that most its users have already migrated to `10.4`. In `10.4`, Budgie greatly changed the UI. Mixing old and new styles is confusing.
~Unity 7~ | ~It's abandoned by Canonical. I suppose that most its users have already migrated to other DEs.~ **UPDATE:** Unity 7 is more likely to be maintained by the [community based team](https://launchpad.net/~unity7maintainers). So let's keep supporting it.
~Metacity (?)~ | ~As far as I know, MATE's Marco was a only WM still using the Metacity theme in 2018. But in the new version of Marco, it's no longer used. (Except for the older versions of MATE/Marco users,) who still uses the Metacity themes today?~ **UPDATE:** It seems I was wrong. MATE 1.20 still uses the Metacity theme by default.

I'm planning to drop these support this summer. For users who are using these old components, you will be able to keep using the old version of Materia.

Please leave a comment if you have any objections or problems to any of these.

**Comment by arnSky** [comment]
Greetings @nana-4 ,

Would it be possible to continue support for

| DE         | OS                | Ubuntu Support |
|------------|-------------------|----------------------|
|Unity 7.4| Ubuntu 16.04| April 2021         |

As mentioned above, Ubuntu 16.04 will be supported till April 2021,
because it is a Long Term Support release, (at-least) bug fixes and all..

Therefore it is possible that, it might be used for some time,

Personally, I like Unity,
important features being 

- [HUD](https://en.wikipedia.org/wiki/Unity_(user_interface)#User_interface) (searchable application menu), and
-  global menu.

[KDE Plasma](https://en.wikipedia.org/wiki/KDE_Plasma_5) 5.13 comes really close as Unity replacement, but its missing HUD alternative (AFAIK),
and so, I am still using Unity 7.4 / Ubuntu

p.s. thanks for the great theme :+1: :100: :1st_place_medal: ,
it saved a lot of time for me (by helping me avoid wasting hours - theme hopping (which I did every so often before I started using this theme) )

**Comment by arnSky** [comment]
Greetings @nana-4,

Thanks for your reply,

A little saddened by support being dropped for Ubuntu 16.04,
however, am happy for continued Unity Support :+1: , Keep up the great work :1st_place_medal: :1st_place_medal: :1st_place_medal: 

for posterity commit f4eea5b4ad5028a9593c72a50ad564244c38f2d5, seems to be the last commit/version, that still works on `Ubuntu 16.04` / `Unity 7.4`

**Comment by nana-4** [comment]
@arnSky Thanks for your understanding.

By the way, I've made [`gtk-3-18`](https://github.com/nana-4/materia-theme/tree/gtk-3-18) branch that left GTK+ 3.18 support. Though I would not add UI changes on that branch anymore, it may receive hotfix updates if critical bugs occur on GTK+ 3.18.

So if you find a serious problem on GTK+ 3.18, feel free to report the issue. (It'll be not necessarily resolved, though.)
