### ISSUE TITLE
Extra non theme "Active foreground app dot" in dock

### ISSUE THREAD

**Issue by whnr** [nana-4/materia-theme#270]
- Materia version materia-gtk-theme 20180519-1
- GTK+ 3 version 3.22.30
- Distribution (and version): Linux version 4.17.10-1-ARCH
- Desktop environment (and version): Gnome 3.28.2
- Related application: [Dash-to-Dock](https://github.com/micheleg/dash-to-dock/issues/776) Issue 776
- Steps to reproduce: Use dash-to-dock.

The active app in the dock has an extra highlight dot on the right for me. In an older version (with a 3.26 shell I think) It behaved correctly. You can also see, that the windowcounter is below the colored dots as well as a little white dot.

![image](https://user-images.githubusercontent.com/8114817/43369750-a2022218-9362-11e8-8815-93e3641e5f1e.png)

Here is the related [Issue 776 in Dash-to-Dock](https://github.com/micheleg/dash-to-dock/issues/776)

**Comment by PJSingh5000** [comment]
@Whnr,

Why do you say that the dot is extra?
Without the dot, how would you identify which icon represents the app that has currently has focus?

(Note, in your image, the Firefox icon is highlighted because you are hovering over it. But if you move your mouse pointer away from it, it will only have dot(s) on the left side, and will look like all the other apps that are currently running).

If nana-4 wants to change this then there must be a different way to visually distinguish the currently focused application from other running applications. I see two options:
1. One option is to highlighting the currently focused application's icon in the same background color as the hover highlight. (The currently running app would be visually indistinguishable from a hovered app, but the user would know that something is highlighted due to hover, because the mouse pointer would be directly on that icon when hovering).
2. Another option may to be to highlight the currently running app with a background that uses the theme's primary color, but with transparency. This will make it look different than a hovered app icon.

On a side note, I noticed in your screenshot that the colored dots on the left are superimposed on top of white "running" dots. Do you have the Dash-to-Dock extension, and have you (on the Appearance tab in the settings dialog) selected something other than "Default" for the "Customize windows counter indicators" option? For some reason Materia (and other themes) don't seem to play well with this option. Dash-to-Dock and the Theme ~BOTH~ try to draw these dots. The colored dots on the left are from Dash-to-Dock, and the white dots (hidden on the left, visible on the right) are from Materia.

**Comment by whnr** [comment]
Here is a comparison: The standard GNOME-Shell Theme handles it pretty much as expected. Materia screws it up quite a bit. The only changes were:

- Enabling and disabling Dash2Dock
- Switching the Shell theme between Gnome default and Materia

> there must be a different way to visually distinguish the currently focused application from other running applications in the Dock
Usually you don't seem to see the active app without dash2dock when only showing the activities overview. Dash2dock handles the highlighting very well, as shown below.

![comparison](https://user-images.githubusercontent.com/8114817/46731581-5c8c0200-cc8b-11e8-9056-21238115e0b3.png)

**Comment by nana-4** [comment]
So sorry for my late response. I didn't have time to properly investigate this and reply.

I'm placing those white dots assets on the dock just for my aesthetic preferences, because I'm currently not satisfied with the custom indicators provided by dash-to-dock.

(As @PJSingh5000 suggests,) The best solution for me is to hide the Materia's white dots when using a custom indicator. But sadly, it seems there is no way to do it so far. So I decided to report it to dash-to-dock.

Thanks for your report anyway.

**Comment by nana-4** [comment]
Thankfully, a feature request I filed against dash-to-dock may be accepted and merged. Then we will be able to _hide_ the white dots when using a custom indicator.

The PR #319 will be merged when the new version of dash-to-dock is released.

**Comment by PJSingh5000** [comment]
Good news!
