### ISSUE TITLE
gnome-calendar

### ISSUE THREAD

**Issue by hexauniverse** [nana-4/materia-theme#312]
Materia v20181115
GTK+ 3 version: 3.24.1
Arch, 4.18.12
Gnome 3.30

![](https://i.imgur.com/26jujA8.png)

**Comment by nana-4** [comment]
Thanks for the report. Unfortunately, it is difficult to fix this by the theme.

I think this is rather a upstream GTK+ issue.

**Comment by hexauniverse** [comment]
There is a partial solution: 
```
popover entry,
popover button {
    margin-right: 1px;
    margin-bottom: 8px;
}
```

**Comment by hexauniverse** [comment]
Another:
''' 
popover entry,
popover button {
    margin: 8px;
}
'''

**Comment by nana-4** [comment]
That solution will add ugly margins to **all** `popover entry` and `popover button`. So I can't adopt it.

Instead, I might make all (or most) `popover button` _flat_. Since flat buttons don't have drop shadow, they'd look neat in `popover`. (Flattening of `entry` has already been completed in master branch.)

**Comment by hexauniverse** [comment]
> That solution will add ugly margins to all popover entry and popover button
Not necessary:
```
.org-gnome-Calendar popover entry,
.org-gnome-Calendar popover button,
.nautilus-window popover entry,
.nautilus-window popover button {
    margin: 8px;
}
```
> Instead, I might make all (or most) popover button flat
But I think, yes, it's better.
