### ISSUE TITLE
Budgie panel no shadow

### ISSUE THREAD

**Issue by speltriao** [nana-4/materia-theme#314]
![screenshot from 2018-11-19 22-18-33](https://user-images.githubusercontent.com/38846168/48743194-21e19600-ec49-11e8-9cc3-4898e804256c.png)
![screenshot from 2018-11-19 22-18-43](https://user-images.githubusercontent.com/38846168/48743195-21e19600-ec49-11e8-8142-05088e74be8a.png)

Budgie-panel isn't showing any shadows while using materia theme ( It works with any other theme I've tried ). The shadow option is enabled as well.
Screenshots shows the lack of shadow

- Materia version: 20180928-1
- GTK+ 3 version: 3.28.2
- Distribution (and version): Ubuntu 18.04.1
- Desktop environment (and version): Budgie 10.4
- Related application (and version): budgie-panel

**Comment by actionless** [comment]
i think by material design guidelines bottom panel shouldn't have any shadows (the "light" is coming down from the top)

**Comment by speltriao** [comment]
> i think by material design guidelines bottom panel shouldn't have any shadows (the "light" is coming down from the top)

Or at least leave it as an option to the user. Every other material theme ( such as Adapta, Plata) have the shadow on the panel (or at least the option to)

**Comment by nana-4** [comment]
Thanks for the report.

This is by design. In Material design, shadow is one of the most important points, but such panels tend to have no shadow.

See the [Material Design guideline](https://material.io/design/platform-guidance/android-bars.html) for example. Both Android status bar and navigation bar have no shadow.

Therefore, sorry but I won't add the shadow option for the panel, even if other third-party material themes have it.

Instead, I highly recommend you set the "Transparency" option to "Dynamic":

![image](https://user-images.githubusercontent.com/9556384/48976454-4adfac00-f0cb-11e8-9859-1b4611c56f72.png)

This look much Material-ish than adding shadows.
