### ISSUE TITLE
Create a KDE variant with tweaked title-bar and header-bar

### ISSUE THREAD

**Issue by ripefig** [nana-4/materia-theme#320]
![image](https://user-images.githubusercontent.com/45201036/49343585-59a30180-f67d-11e8-9fec-16529dd34467.png)

(A QT app, a GTK CSD app, and a traditional GTK app)

Materia is currently the only theme that has good QT *and* GTK support. It's the only option if you want a consistent theme on KDE. Everything else is just terrible. Materia-gtk needs a couple of tweaks to be seamless with Materia-QT in an KDE environment.

 KDE uses its own decorations for CSD apps. The header and the toolbar should be tweaked just a little to conform with the materia-KDE theme.The header-bar and toolbar should have the same style, with a bottom drop shadow and no top-border. I don't know how modular the code is, but this seems like it would be a very simple modification.

I'd dig into the css code myslef, but I figured I'd ask here first because it would take me way longer to figure it out.

**Comment by ripefig** [comment]
https://github.com/PapirusDevelopmentTeam/materia-kde

**Comment by nana-4** [comment]
Thanks for filing this issue.

The top border (highlight color) on `headerbar` should be a bug. I'll fix that.

**Comment by nana-4** [comment]
> The header-bar and toolbar should have the same style

I agree. In KDE, GTK+ `toolbar`, `headerbar`, and Qt toolbar should have the same style.

I think you (@ripefig) are thinking something like this:

![image](https://user-images.githubusercontent.com/9556384/49353713-84836900-f702-11e8-8bab-4bf0e3f46ce6.png)

However, in GNOME, the traditional `toolbar` looks like this with Materia:

![image](https://user-images.githubusercontent.com/9556384/49353125-581a1d80-f6ff-11e8-999a-0b4c1bb311f4.png)



For 3 reasons:

- GTK+ traditional toolbars tend to use full-color icons instead of symbolic icons. So the full-color icons may look a bit ugly with dark(er) titlebar background colors.
- In GTK2 & GTK3 theming, it's impossible to add drop shadows to the traditional `toolbar` so far.
- **In Material Design guidelines, titlebar background color is never used for such toolbars.** See some mockups from Material Design guidelines for example ([A](https://storage.googleapis.com/spec-host-backup/mio-design%2Fassets%2F1Fn8GUmDJjnO2PDVgrZbI19JwV78TlukJ%2Ftabs-placement-ui.png), [B](https://storage.googleapis.com/spec-host-backup/mio-design%2Fassets%2F1TaxymtZ-I0U8XTqPmxIrlXN990WwuTEP%2Fsingle-line-desktop.png), [C](https://storage.googleapis.com/spec-host-backup/mio-design%2Fassets%2F0B54x0KDcs5U-NC1tYmRKQWIzdDA%2Fbehavior-icon.png)).

So I believe something like this should look more appropriate and clean in KDE:

![image](https://user-images.githubusercontent.com/9556384/49355162-a0d6d400-f709-11e8-922b-fccfd2311d7a.png)

What do you think?

/cc @varlesh @SmartFinn @PapirusDevelopmentTeam

**Comment by varlesh** [comment]
@ripefig We use aurorae decoration. I'm not understand what you want:
![image](https://user-images.githubusercontent.com/8083855/49358137-13848700-f6eb-11e8-9d3d-e4b186bcd841.png)
![image](https://user-images.githubusercontent.com/8083855/49358279-868dfd80-f6eb-11e8-8dc8-dc1d8757cc83.png)

**Comment by nana-4** [comment]
> We use aurorae decoration.

Sorry, I don't understand "aurorae decoration" as I'm not familiar with KDE theming. Do you mean that the color of titlebar & toolbar are always same in the aurorae decoration?

> I'm not understand what you want

In order to follow the Material Design guidelines as possible, I was thinking about changing the toolbar style like this:

![image](https://user-images.githubusercontent.com/9556384/49359880-d0daa300-f71a-11e8-9fb5-129ed7283f67.png)

But in Dolphin, indeed the current style may look better... I'll rethink about the style.

**Comment by varlesh** [comment]
We use toolbar with shadow and decoration color, because impossible use CSD for KDE/Qt-apps and we don't want change this, because this spoil style.
I knwo, GTK2 not use CSD too... but now more apps migrate to GTK3 and Material Design for GTK2 impossible too.

**Comment by nana-4** [comment]
@varlesh OK, I understand. Thank you for your clarification!

As a side note: As shown in the [Google's mockup](https://storage.googleapis.com/spec-host-backup/mio-design%2Fassets%2F1Fn8GUmDJjnO2PDVgrZbI19JwV78TlukJ%2Ftabs-placement-ui.png) I presented as an example, drop shadow is not always necessary in toolbar. And I think [Materia GTK2 theme](https://user-images.githubusercontent.com/9556384/49363108-210a3300-f724-11e8-9ef8-1732b2529408.png) already looks like Material Design enough :wink:

**Comment by ripefig** [comment]
@nana-4 I'd prefer the first mock up with the shadow:

![image](https://user-images.githubusercontent.com/45201036/49368628-33727580-f700-11e8-8767-a2ff34ca131e.png)

This requires just the GTK theme to be changed. The second flatted design means that both QT and GTK themes need to be changed.

It may also be a good idea to get rid of the double-title issue but making the the title text in the header invisible.

@varlesh I am saying, make the Materia-GTK headerbar and toolbar both look like the Materia-KDE toolbar.

**Comment by nana-4** [comment]
Okay, I decided not to change both `toolbar` & `headerbar` style for now. The reason is as mentioned above. (Although I'll fix the "top-border" in the repo.)

@ripefig So you'll need to change the style manually, if you want. Try pasting the following code to `~/.config/gtk-3.0/gtk.css` (or bottom line of `/usr/share/themes/Materia-light-compact/gtk-3.20/gtk.css`):

```css
toolbar:not(.osd) {
  background-color: #E0E0E0;
  box-shadow: 0 1px 1px rgba(0, 0, 0, 0.12), 0 1px 2px rgba(0, 0, 0, 0.24); /* not working */
}

headerbar {
  box-shadow: 0 1px 1px rgba(0, 0, 0, 0.12), 0 1px 2px rgba(0, 0, 0, 0.24); /* to get rid of highlight */
}
```

Note: As I already mentioned, you wouldn't be able to add drop shadows to `toolbar` even with the code.

**Comment by nana-4** [comment]
> The second flatted design means that both QT and GTK themes need to be changed.

Yes, I _was_ intending it. (But it was abandoned now.)

> It may also be a good idea to get rid of the double-title issue but making the the title text in the header invisible.

I'm sure it's not theme issue, but upstream issue. Though you can locally get rid of the title text with this:

```
headerbar .title { font-size: 0; }
```

**Comment by ripefig** [comment]
@nana-4 thanks for the code. End result of your patch +  gtk-no-csd + global menu: 

![image](https://user-images.githubusercontent.com/45201036/49442189-ca5f3080-f7d9-11e8-9aa9-5a837444c744.png)

It looks perfect. Check it out @varlesh.

This obviously a whole series of hacks to get around the CSD/SSD feud, but the end result works beautifully.

**Comment by nana-4** [comment]
Good for you :) Then I'm gonna close this.

**Comment by ripefig** [comment]
I would still suggest packaging this solution. It's works great but regular users won't have access to it. Up to you of course.
