### ISSUE TITLE
Some panel buttons are oval with the big font size

### ISSUE THREAD

**Issue by actionless** [nana-4/materia-theme#332]
**Reporter Info**

- Materia version: 
- GTK3 version: GTK+ 3.24.2
- Distribution (and version): Arch Linux
- Desktop environment (and version): -
- Related application (and version): Nemo 4.0.6

**Actual Issue**

![2018-12-20--1545264491_709x704_scrot](https://user-images.githubusercontent.com/1655669/50255810-be878700-03f3-11e9-8472-746be3e11414.png)

**Additional info**

In nautilus it's even more weird behavior (but it's noticeable only on mouse hover):
leftmost button is circle, but all the buttons on the right side are oval-shaped

**Comment by actionless** [comment]
it's from my laptop, it have about 150 dpi per inch, so it's not enough to use hidpi scaling, so gtk scaling is 1.0

**Comment by nana-4** [comment]
> it's from my laptop, it have about 150 dots per inch, so it's not enough to use hidpi scaling, so gtk scaling is 1.0

Maybe in such a situation, [fractional scaling](https://wiki.archlinux.org/index.php/HiDPI#Fractional_Scaling) would be useful (though I'm not sure whether it works properly outside of GNOME).

> btw most of the apps are looking quite fine in that setup, only with some panel buttons there is this oval problem

Perhaps it's because there are text-buttons on the containers. In Materia, most buttons have `24px` `min-height` as well as upstream Adwaita. Therefore, when the font `line-height` is over `24px`, the button height will be changed accordingly. Similarly in Adwaita, the icon buttons would be transformed from square to rectangle.

This theme is not designed to be used with huge font size, so please consider using "fractional scaling" or smaller font size.
