### ISSUE TITLE
Question: Ripple animation

### ISSUE THREAD

**Issue by vredesbyyrd** [nana-4/materia-theme#335]
Thanks for developing and maintaining this great theme. I am playing around with making one based on Materia for personal use and have a question regarding the ripple animation present on tabs, buttons etc. If possible I wanted to add the same animation thats displayed when clicking a _Nautilus_ sidebar location button to the _Lollypop_ 'artist' sidebar. I spend a lot of time in lollypop, and since that animation is present in most major sidebars it would be nice for consistency. I cannot figure out how to implement it though. 

Do you know if this would be possible? Any tips you may have would be appreciated. 

Thanks for your time. 

![screenshot from 2018-12-21 19-57-18](https://user-images.githubusercontent.com/22080838/50369728-a765a800-055f-11e9-907d-5bdbe239d4df.png)

**Comment by nana-4** [comment]
Unfortunately, adding the ripple animation to the Lollypop sidebar is impossible.

Nautilus sidebar has `row` which is animatable.
On the other hand, Lollypop sidebar has `treeview.view`  which is non-animatable.

See https://wiki.gnome.org/Projects/GTK/StyleClasses
This is because the CSS node conversion is not yet completed in GtkTreeView.

If the Lollypop sidebar gets to have `row` instead of `treeview.view` like Nautilus, it would have the ripple animation.

**Comment by vredesbyyrd** [comment]
Ahhhhh, I see. That would explain it, unfortunate but good to know.  Thank you for the detailed explanation and link. I will read it more thoroughly :)   

Cheers.
