### ISSUE TITLE
Change selection foreground color

### ISSUE THREAD

**Issue by gnunn1** [nana-4/materia-theme#338]
- Materia version: Master (git clone)
- GTK3 version: 3.24.2
- Distribution (and version): Arch Linux
- Desktop environment (and version): Gnome 3.3.0 
- Related application (and version): All

**Description**

Thanks for a great theme and the ability to easily change the colors of the theme. I'm trying to create a theme that mimics Sam Hewitt's old Orchis theme colors and I need to be able to set the selection background and foreground. At the moment it looks like change_colors.sh only supports the SEL_BG tag with no coverage of SEL_FG.

In the Orchis theme it uses a light background (EFEFEF) with a dark text color (555555) and a dark selection color (A348B1). Using these colors the selection text is unreadable since it is a dark color against a dark selection color. What I would like to do is have the selection color appear as white.

I'm able to make it work by a bit of acting, essentially modifying the inverse_color in _colors.scss.template to use a SEL_FG token and including it in change_colors.sh. It's not perfect though as some things still need to be tweaked in the resulting gtk.css that is generated.

The out of the box materia theme seems to do this already with the selection color being a dark blue and the selection text being white. This makes me wonder if I'm missing something Captain Obvious to be able to do the same thing with my own color scheme.

Here is the command I am using to generate the theme:

```
./change_color.sh -o Orchis <(echo -e "BG=EFEFEF\nFG=555555\nHDR_BG=555555\nHDR_FG=FFFFFF\nMATERIA_VIEW=EFEFEF\nMATERIA_SURFACE=DEDEDE\nSEL_BG=A348B1\nSEL_FG=FFFFFF\nMATERIA_SELECTION_OPACITY=1.0\nMENU_BG=EFEFEF\nMENU_FG=FFFFFF\nMATERIA_STYLE_COMPACT=False\n")
```

**Comment by nana-4** [comment]
Since this is a Material Design theme and in order to follow the guidelines more accurately, I've changed the selection style based on the [States guidelines](https://material.io/design/interaction/states.html#selected) on the `master` branch. Therefore it is intentional that `change_colors.sh` only supports the `SEL_BG` tag with no coverage of `SEL_FG`. Instead, you can change the selection opacity with `MATERIA_SELECTION_OPACITY` if you feel the default selection opacity (`0.32`) is too weak.

Since this is a Material Design theme, can you try getting used to the semi-transparent selection background with no selection foreground change?

For better contrast of the selection text, I'd recommend to make `FG` darker (e.g. `212121`):

```
./change_color.sh -o Orchis <(echo -e "BG=EFEFEF\nFG=212121\nHDR_BG=555555\nHDR_FG=FFFFFF\nMATERIA_VIEW=FFFFFF\nMATERIA_SURFACE=FFFFFF\nSEL_BG=A348B1\nMATERIA_STYLE_COMPACT=False\n")
```

What do you think?

**Comment by gnunn1** [comment]
Thanks, I tried it and it looks OK so thanks for the suggestion. I will say though that I do prefer a solid selection color rather then one relying on opacity, but I can get used to this so it is not a big deal. Thank you for your assistance, much appreciated.
