### ISSUE TITLE
PPA package for Ubuntu 16.04 should stay in v20180928

### ISSUE THREAD

**Issue by Netroxen** [nana-4/materia-theme#344]
**Reporter Info**

elementaryOS Loki 0.4
GTK 3 \- 3.18.9\-1ubuntu3.3
GTK 2 \- 2.24.30\-1ubuntu1.16.04.2
materia\-gtk\-theme - 20181125\-4\-0ubuntu1\~xenial1
Linux 4.15.0\~43\-generic

**Actual Issue**

Since making a system update the last days, the Materia theme appears broken. Specifically certain borders are now transparent, the toolbar icons are now black when they were white and there are white / black borders between interface elements.

![snap_2019_01_08](https://user-images.githubusercontent.com/7691449/50818993-0af62080-1329-11e9-9551-a7dcd5d25907.png)

**Additional Info**

I have made sure that `gtk2-engines-murrine` and `gnome-themes-standard` are installed and updated, I also tried removing and purging Materia and then trying to install it again, but to no avail.

**Comment by nana-4** [comment]
Thanks for your report.

This is because elementaryOS Loki 0.4 uses GTK+ 3.18, whereas Materia `v20181125` no longer supports GTK+ 3.18. (Materia has dropped support for GTK+ 3.18 after releasing [`v20180928`](https://github.com/nana-4/materia-theme/releases/tag/v20180928).)

@igor-dyatlov Could you please update the only xenial (Ubuntu 16.04) package to `v20180928` to fix this? Or maybe, we should no longer introduce and maintain the package for Ubuntu 16.04. What do you think?

**Comment by ArchangeGabriel** [comment]
@Netroxen Another solution would be for you to upgrade to ElementaryOS 5.0. ;)

**Comment by Netroxen** [comment]
> @Netroxen Another solution would be for you to upgrade to ElementaryOS 5.0. ;)

I have to get round to it, but I'm using the system in a production environment and I just don't have the time at the moment to get around to it. I'll see if I can downgrade the package somehow then...

**Comment by actionless** [comment]
> ElementaryOS

> (theme broken after update)

> I'm using the system in a production environment


i am just wondering what kind of service are you hosting in production from that machine :-)

**Comment by Netroxen** [comment]
> > ElementaryOS
> 
> > (theme broken after update)
> 
> > I'm using the system in a production environment
> 
> i am just wondering what kind of service are you hosting in production from that machine :-)

Let me reiterate, I'm using the system for myself, at work. Just don't see any reason to upgrade when everything is running fine, I'll need to make some time to jump ship though... Just not right now...

**Comment by nana-4** [comment]
@igor-dyatlov Bump. Are you not interested in maintaining the PPA package anymore? If so, I'm going to stop introducing the outdated PPA from the README.

**Comment by k1nghat** [comment]
@nana-4 it looks like the repo has the latest version (v20190201): https://launchpad.net/~dyatlov-igor/+archive/ubuntu/materia-theme

![image](https://user-images.githubusercontent.com/16073360/52905530-221a0f00-3201-11e9-95b4-56f1ea945b84.png)

**Comment by qwertyuser1983** [comment]
I think this may related. In my case, I change to Materia Ubuntu Dark because several buttons, radiobutton, checkboxes, and textbox in Materia Dark is became invisible. Using Firefox became very difficult because we can't see what we are writing. 

Bodhi Linux 16.04
Igor PPA
Materia KDE from Papirus

**Comment by igor-dyatlov** [comment]
@nana-4 I update the repository whenever possible. I follow the current version.

**Comment by nana-4** [comment]
(Sorry for the late reply. I was inactive recently.)

> latest version
> current version

Well, in this case that is the problem. The packages for Ubuntu 16.04 should **not** be updated to the latest version, because the current version of Materia doesn't support Ubuntu 16.04 and GTK 3.18.x anymore. (As described [here](https://github.com/nana-4/materia-theme/releases/tag/v20180928), v20180928 is the last version to support GTK 3.18.)

I mean, `20190201-5-0ubuntu1~xenial1` needs to be **downgraded** to `20180928-5-0ubuntu1~xenial1`.

**Comment by nana-4** [comment]
As above, I removed the mention of the Ubuntu 16.04 package from the README.

Closing.
