### ISSUE TITLE
Materia Dark selection opactiy

### ISSUE THREAD

**Issue by duhok1** [nana-4/materia-theme#346]
- Materia version: Oomox created
- GTK3 version: 3.24.2
- Distribution (and version): Arch Linux
- Desktop environment (and version): Cinnamon 4.09
- Related application (and version): Oomox git (13012019)

**Actual Issue**

On some GTK windows (in example below, Dropbox upload  window) the selected text is less readable (see left), while the normal  behavior (right side) is as desired. 

The Materia-Dark was created with latest Oomox version from git.

Screenshot attached.
![51089340-90b70900-1739-11e9-9dfb-a4ac10f1d422](https://user-images.githubusercontent.com/46654846/51090258-2f963200-1747-11e9-9853-507764f6856f.png)

**Comment by nana-4** [comment]
Thanks for the report.

Indeed, with that color scheme, the selected text looks less readable. However, to be honest, I'm not very positive in changing the design itself because the design is in line with Material Design Guidelines.

Could you try to increasing the lightness of the `Selection Color` and decrease the `Selection Opacity` with the Oomox GUI and test somehow it looks better?

**Comment by duhok1** [comment]
Seems good with the new upstream release. Thank you! Closing this.
