### ISSUE TITLE
Slider buttons get 'stuck' in an active state  

### ISSUE THREAD

**Issue by vredesbyyrd** [nana-4/materia-theme#349]
**Reporter Info**

- Materia version:  commit 6386a791691e15ae0307836d134a05e91dd8ecbf
- GTK3 version:  3.24.4
- Distribution (and version):  Arch (kernel 4.20.3-1)
- Desktop environment (and version):  Budgie 10.5

**Actual Issue**

The animation on slider buttons seems to get stuck in an active / hover state.  In the attached gif I used Lollypops progress bar as an example, but It's also  present with all volume sliders I have tried. Clicking another button or application window will _sometimes_ release the animation to its proper inactive state. I have poked around trying to figure out the cause but thus far had no luck. 

![peek 2019-01-23 17-19](https://user-images.githubusercontent.com/22080838/51643725-23725780-1f33-11e9-84ef-27e1ce112411.gif)

Another possibly related issue: Certain switches display in an odd state, E.g the top switch in the below screenshot.  I cannot find any rhyme or reason why. 

![screenshot from 2019-01-23 16-53-20](https://user-images.githubusercontent.com/22080838/51643812-849a2b00-1f33-11e9-83aa-5010801ba9c7.png)

**Note** 

I also built stock Materia from master and the same behavior is present. 

Thank you for your time and work.

**Comment by nana-4** [comment]
Hi,

This is intentional design based on the [Material Design guidelines](https://material.io/design/interaction/states.html#focus). It indicates a **focus** state, not an  _active_ or _hover_ state.

For example, in the screenshot below, it indicate that you can turn on the switch by pressing <kbd>Enter</kbd> key.

For your reference, Adwaita indicates the focus state with *dashed outline*, while Materia indicates it with the background-color changes.
