### ISSUE TITLE
Combo Entry Underline is Not Colored

### ISSUE THREAD

**Issue by PJSingh5000** [nana-4/materia-theme#365]
The combo entry underline is black, but the widget-factory preview on the Materia-theme home page shows a colored underline.

This is the preview on https://github.com/nana-4/materia-theme...
![combo_entry_with_color_underline](https://user-images.githubusercontent.com/19394936/54571103-90e0b880-49b7-11e9-8ab4-e20dfafa9a40.png)

This is what I see...
![combo_entry_with_black_underline](https://user-images.githubusercontent.com/19394936/54571108-96d69980-49b7-11e9-9f77-fdc4ad878927.png)

Is the image on the Materia home page outdated, or is this a bug in materia theme?

I am using Materia version 9e8c164cfa5113309b601ae549f80a5e1875abe0.
My libgtk-3-0 version is 3.24.1-1ubuntu2.
This is on Ubuntu 18.10.

I prefer the colored underline.

If this is not a bug in Materia, what can I change to make underline for hovered combo entrys...

- have the primary color?
- be thicker

...as in the image shown on the Materia-theme home page?

**Comment by PJSingh5000** [comment]
Update:

This issue is only with drop-down combo boxes (GtkComboBox).

The entry fields (GtkEntry) are fine and do have the thick "blue" underline when hovered.

Here is a screenshot of a text entry field (GtkEntry) from a file chooser dialog showing the colored underline...
![Screenshot from 2019-03-18 22-09-17](https://user-images.githubusercontent.com/19394936/54575547-da86ce80-49ca-11e9-8913-67656706885d.png)

And here is the Gnome Tweaks window with combo boxes (GtkComboBox). Notice, the underline is a thin black line when hovered...
![Screenshot from 2019-03-18 22-18-02](https://user-images.githubusercontent.com/19394936/54575782-d8713f80-49cb-11e9-82a8-7ebd8aab62b0.png)

**Comment by nana-4** [comment]
This is by design, not a bug. While the 1px black underline indicates the **hover** state (`button.combo:hover`), the 2px blue underline indicates the **focus** state (`entry:focus`). (Please note that [in GTK3, GtkEntry can't have hover state](https://gitlab.gnome.org/GNOME/gtk/issues/196).)

But yeah, I agree the current hover style isn't very good. Also it's a bit outdated, according to the [current Material Design Guidelines](https://material.io/design/components/text-fields.html#filled-text-field):

![image](https://storage.googleapis.com/spec-host-backup/mio-design%2Fassets%2F1TKi-wOcOI4c_XQswgLFfHS1078d1wAzJ%2Ftextfields-filled-states.png)

I'll update the hover style of the combo button soon :D

**Comment by nana-4** [comment]
Done with 5d216a75f590948b9c1e5468bbde296c232f27e9.

If you still prefer the colored underline when hovering, you can do it by replacing [_common-3.20.scss#L951](https://github.com/nana-4/materia-theme/blob/5d216a75f590948b9c1e5468bbde296c232f27e9/src/_sass/gtk/_common-3.20.scss#L951) from

```scss
&:hover { background-image: image($overlay-hover); }
```


to 

```scss
&:hover { @include entry(focus); }
```
