### ISSUE TITLE
Materia-dark does not change the color of the menus in chrome.

### ISSUE THREAD

**Issue by freefreeno** [nana-4/materia-theme#367]
**Reporter Info**

- Materia version: 
- GTK3 version: 
- Distribution (and version): 
- Desktop environment (and version): 
- Related application (and version): 

**Actual Issue**

**Steps to Reproduce**

1. 
2. 
3. 

**Additional Info**

My bad but I am leaving this here for others. Go into chrome settings after installing the materia-gtk theme in KDE and set windows to use gtk and the go into KDE settings and disable window borders for chrome. You may want to let people know this because without these steps you will have a really weird looking chrome.

**Comment by nana-4** [comment]
Sorry for not replying sooner. But this seems to be an issue common to all dark Chrome themes (not specific to Materia-dark), so I would like to close this as an upstream issue.

**Comment by memeplex** [comment]
I don't think so, using gtk-level materia dark theme makes chrome menu dark, using chrome-level materia dark theme (which I think this report is about) with chrome built-in light theme makes the menus light. Of course, there is no point in using the gtk-level materia dark theme in chrome at the same than the chrome-level materia dark theme, because many shortcomings the chrome-specific theme fixes are then lost. When I say "at the same time" I mean, install the chrome-specific materia dark theme over one or other base theme (materia dark gtk-level or built-in).

**Comment by nana-4** [comment]
??? I think you are misunderstanding something. As far as I know, **there is no combination** in Chrome "color scheme" theme. (I mean, Chrome-level theme with GTK-level theme, or Chrome-level theme with built-in theme.) Basically, both GTK-level theme and Chrome-level theme only change the color scheme of Chrome. And neither can change the color scheme perfectly as we wish. Both have different shortcomings. While GTK-level theme loads background-color of GtkMenu properly, in Chrome-level theme the background of the menu is hard-coded to white. Try installing other dark themes from Chrome Web Store. The menu should always be white in any Chrome theme. Therefore this is an upstream issue.
