### ISSUE TITLE
Close buttons on GNOME 3.32.1 css issue

### ISSUE THREAD

**Issue by jeroenroumen** [nana-4/materia-theme#381]
**Reporter Info**

- Materia version: 
- GTK3 version: 3.24.8-1ubuntu1
- Distribution (and version): Pop!_OS 19.04
- Desktop environment (and version): GNOME 3.32.1
- Related application (and version): Close buttons Activities

**Actual Issue**

**Steps to Reproduce**

1. Go to Pop!_OS 19.04 desktop
2. Install and switch to Materia shell theme through GNOME tweaks
3. Hit the super button to open activities and see the close button from the Pop theme and Materia show up.

![IMG_20190515_164734](https://user-images.githubusercontent.com/17384485/57853134-462bc300-77e5-11e9-9845-9bc682823b12.jpg)

**Comment by nana-4** [comment]
Thanks for your report. 

This is because Pop!_OS has a custom-made GNOME Shell theme in "Pop session". However, Materia does not support GNOME sessions customized by downstream distro.

To resolve this issue on your distro, please install `gnome-session` and then switch to "GNOME" or "GNOME on Xorg" session in the login screen. (In other words, Materia won't support "Pop session", sorry.)

**Comment by jeroenroumen** [comment]
Actually the same problem is showing with your solution. Even with the default GNOME on Xorg session on Pop the closed buttons are now showing correctly. I tried it out in a virtual machine with a fresh Pop!_OS 19.04 installation.

**Comment by nana-4** [comment]
How did you install Materia? Manually? Or from the distro package? What is the version?

Maybe the Materia you installed is an old version that does not support GNOME Shell 3.32.x.
