### ISSUE TITLE
GTK svg inconsistency

### ISSUE THREAD

**Issue by ddnexus** [nana-4/materia-theme#384]
Hi @nana-4 
I noticed a few inconsistencies with colors and shapes  the in the `src/gtk/assets.svg` file:

- the `selectionmode-checkbox-unchecked-dark` is using the surface dark color instead of the lighter secondary-disable gray
- the `selectionmode-checkbox-unchecked-dark` is using the same darker blue used for the light version instead of the lighter blue used for dark
- the shape uses an extra checkmark shape (always white for both dark and light) instead of a see through hole (as used for checkboxes in the `src/gtk-2.0/assets-dark.svg` file)

Is that intentional? If it is why? If it is not, I can provide a PR to make it consistent. Please, let me know.

**Comment by nana-4** [comment]
Hi @ddnexus, thanks for your suggestions.

First of all: Yes, that is intentional. We're currently using the [surface](https://material.io/design/environment/surfaces.html)-style instead of the [icon](https://material.io/design/iconography/system-icons.html)-style for the selection-mode checkboxes. While I also think that ideally it's better to use the icon-style, in reality it's not reasonable in (some) GTK apps. The reason is overlapping _flat_ icons on _raised_ items (i.e. 0dp surface on 1dp surface) goes against [Material Design guidelines](https://material.io/design/environment/elevation.html#depicting-elevation), and doesn't look good. For example:

![image](https://user-images.githubusercontent.com/9556384/58007609-9a0c1400-7b25-11e9-89df-cff5464f04a2.png)

So...

> the `selectionmode-checkbox-unchecked-dark` is using the surface dark color instead of the lighter secondary-disable gray

It's intentional, as the checkbox has surface-style (like regular buttons).

> the `selectionmode-checkbox-unchecked-dark` is using the same darker blue used for the light version instead of the lighter blue used for dark

Yes, I know it's a bit odd, but using the light blue means that we need a **dark** checkmark on the light blue surface:

![image](https://user-images.githubusercontent.com/9556384/58008876-46e79080-7b28-11e9-84ca-4961f1eee6ff.png)

In my first impression, I thought the dark checkmark looks inconsistent on the dark theme. But maybe I need to reconsider this because in the recently released [Dark Theme guideline](https://material.io/design/color/dark-theme.html), dark text color is recommended on the light primary color.

> the shape uses an extra checkmark shape (always white for both dark and light) instead of a see through hole (as used for checkboxes in the `src/gtk-2.0/assets-dark.svg` file)

From my understanding, in Material Design, a see through hole makes sense for _symbolic icons_, but not for _surfaces_.

If you have any other suggestions or ideas, please feel free to comment :)

**Comment by ddnexus** [comment]
Wow! It's always a pleasure to read your answers, and learn... Thank you.
Now I understand the context that checkbox is used and it makes sense.

About the dark checkmark for dark themes, now that you added the `on` function I experimented it with some colors and it gave me the dark text for buttons... (because the color of my buttons is darker than 128). It looks more appropriate and I like it more than what I was using before.

Maybe the primary color used for the dark theme in Materia is a bit too bright, giving a very high contrast and the on function gives a white text. You may want to experiment with a darker primary for dark.

While at it, I also noticed that you used the $primary-dark in certain styles (and also a fixed $primary-light somewhere else IIRC) instead of using always the $primary (decided on the dark/light theme in the _color.scss). That made me scratch my head: shouldn't you use a single primary for the whole theme, avoiding to have mixed primaries colors in the same theme?

**Comment by nana-4** [comment]
Thanks for your feedback, and sorry for my late reply.

> Maybe the primary color used for the dark theme in Materia is a bit too bright, giving a very high contrast. You may want to experiment with a darker primary for dark.

Since primary color is also used for some text colors, for dark theme we need a light primary color to a certain extent to ensure legibility. (See the [dark theme guideline](https://material.io/design/color/dark-theme.html) for details.) But thanks, I'll keep it in mind.

> shouldn't you use a single primary for the whole theme, avoiding to have mixed primaries colors in the same theme?

No, Material Design allows you to use lighter or darker variants of primary color in the same theme depending on the situation. See: https://material.io/design/color/#color-theme-creation

> *You can make a color theme for your app using your primary color, as well as dark and light primary variants.*

But in dark theme, maybe I should use a single primary color as per the dark theme guideline. This is a difficult issue given the consistency with the standard theme variant, though. I'll consider about this while testing. :)

Anyway, the color scheme is a more general issue and different from OP, so I'm going to close this issue for now.

**Comment by ddnexus** [comment]
Thank you for your reply. I would like to follow up on the color scheme: I have a possibly useful slight modification to discuss. If you are interested... should I open a new issue or do you prefer any other way to discuss it?

**Comment by nana-4** [comment]
Thank you! I'd love to hear your thoughts!
Yes, please open a new issue :)
