### ISSUE TITLE
gtk unified window title bar 

### ISSUE THREAD

**Issue by nbouchin** [nana-4/materia-theme#386]
- Materia version: 20190315
- GTK3 version: 
- Distribution (and version): fedora 30
- Desktop environment (and version): Gnome 3.32.2
- Related application (and version): telegram, firefox, discord...

Hy, is there a way to unify all window title bar?
Some like telegram, firefox or discord have different padding.

firefox on left, gnome-file on the right:

![Screenshot from 2019-05-21 23-35-17](https://user-images.githubusercontent.com/40028878/58132282-24856e00-7c21-11e9-9cd7-2671daafd91a.png)

**Comment by nana-4** [comment]
That's an intentional styling, but you can break it by editing the GTK CSSs as following.

1. Open `/usr/share/themes/Materia-compact/gtk-3.0/gtk.css` and `/usr/share/themes/Materia-compact/gtk-3.0/gtk-dark.css` with your text editor.
2. Search `.default-decoration`.
3. Remove all sizing factor from `.default-decoration` like this:
```diff
 .titlebar.default-decoration {
-  min-height: 24px;
-  padding: 4px;
   box-shadow: inset 0 1px rgba(255, 255, 255, 0);
 }

 .tiled .titlebar.default-decoration,
 .maximized .titlebar.default-decoration,
 .fullscreen .titlebar.default-decoration {
   box-shadow: none;
 }

 .titlebar.default-decoration button.titlebutton {
-  min-height: 24px;
-  min-width: 24px;
-  margin: 0;
-  padding: 0;
 }

 .background:not(.csd) .titlebar.default-decoration button.titlebutton:active {
   background-size: 1000% 1000%;
 }
```

4. If you are on "GNOME on Xorg" session, reload gnome-shell by pressing <kbd>Alt</kbd>+<kbd>F2</kbd> then typing `r`.

**Comment by nbouchin** [comment]
Thanks a lot for the answer :+1:
