### ISSUE TITLE
Single primary color in dark variant

### ISSUE THREAD

**Issue by ddnexus** [nana-4/materia-theme#388]
Hi @nana-4,
talking about the single or light/dark primary color... I understand what you said about having a darker and a lighter color for different needs, and it makes sense, but IMO it would be better having a single primary color. 

If it is used for text and it is not readable, then I think that the combination of background foreground should probably be restyled, maybe avoiding the primary, or - in extreme and desperate cases :) - using a SCSS function to generate a shade of it as needed.

If you search for the usage of $primary-light and $primary-dark in the scss files you see that it is really seldom used. That is a good indicator that a simplification (i.e. replacing the current 3 primary colors in the scss with a single one) would be beneficial.

Currently we have 2 (possibly) different original colors per theme-color (e.g. 2 for light and 2 for dark), and they are similar but not the same, nor a shade of each other... which in graphic design is not a good thing :).

HTH

**Comment by nana-4** [comment]
Thanks for filing the issue :+1: 

I think you are talking about this in terms of simplification and consistency, but we also have to take into account the **accessibility**.

From the viewpoint of accessibility, having a single primary _in dark variant_ would make sense, because its backgrounds are *always* dark (with rare exceptions).

However, in light variants the backgrounds are not always light. They (standard and -light variants) can have dark backgrounds in some parts (especially panels). Using dark primary on dark background is not accessible, and not recommended in the Material Design guidelines. This is why light variants have lighter primary along with normal primary. (This is similar to the light variants having light text colors along with dark text colors.)

So, at least in the light variants, I'm going to keep the status quo. Also...

> maybe avoiding the primary

Sorry, but I won't. It's also not recommended in the [Material Design guidelines](https://material.io/design/components/snackbars.html#anatomy):

> To distinguish the action from the text label, text buttons should display colored text.

> Don’t.
> The text label shouldn’t share the same color as the text button.

Therefore, I would like to discuss here whether we should have a single primary color **in dark variant** :)

**Comment by nana-4** [comment]
## Summary

Here is the current color scheme of the dark variant; we have a light primary color:

![image](https://user-images.githubusercontent.com/9556384/58383494-a1925800-8012-11e9-8215-b84ce8cb665f.png)

Currently, however, dark primary color is also used only for the suggested action button and selection mode headerbar. I'm not sure which is better:

with dark primary color | with normal primary color
--- | ---
![image](https://user-images.githubusercontent.com/9556384/58384379-1ddd6900-801c-11e9-9b95-956a20c933e5.png) | ![image](https://user-images.githubusercontent.com/9556384/58384434-7b71b580-801c-11e9-833a-f33f7c12cde0.png)
![image](https://user-images.githubusercontent.com/9556384/58384537-b1fc0000-801d-11e9-95d9-8e17b190c4b4.png) | ![image](https://user-images.githubusercontent.com/9556384/58384674-7e21da00-801f-11e9-8744-420a4a9e8ab2.png)

- The advantage of dark primary color is the **text color** is consistent in light color within the whole dark variant.
- The advantage of normal primary color is the **primary color** is consistent within the whole dark variant.

In the recently released [dark theme guideline](https://material.io/design/color/dark-theme.html), consistent light primary color is used for the button background as well. So maybe we should follow that.

But before doing that, I would like to get some feedback (especially from dark variant users!) because I'm not using dark variant on a daily basis :)

**Comment by ddnexus** [comment]
Thanks for the detailed explanation! Indeed, since I am using only dark and low contrast/saturation themes (due to an unfortunate sight problem) I was forgetting that other styles have dark and light elements.

So, pure dark and pure light styles/themes (which I naturally prefer because I am a consistency freak :)) can have a single primary, but since we have also mixed element styles, the 2 different primaries are needed. That hurts me, but it makes sense. :) 

However since they might be used in the same theme, displayed side by side, I would recommend using the same color hue, with 2 different brightness (and eventually a bit of saturation adjustment if really needed).

As for the dark text on dark theme buttons: as I already said, I was using a light text on dark theme buttons in Equilux, but when your new `on` function assigned the dark color on the button, I liked it more, and it makes sense. Coincidentally it is also the dark theme recommendation so I would definitely go for that style.

**Comment by nana-4** [comment]
Thanks for your suggestion. Now I've decided to go with a single (light) primary color in dark variant :)
