### ISSUE TITLE
[suggestion] Improve close buttons in Metacity/Xfwm/etc.

### ISSUE THREAD

**Issue by DarthWound** [nana-4/materia-theme#391]
To have crisper/sharper close buttons, and to have better consistency, a subtle change could really improve them. Just add another pixel at each endpoint, like this:

![impclose](https://user-images.githubusercontent.com/1771322/58561284-10e09580-8227-11e9-9c56-45cdd431a7fa.png)
_(zoomed in - zoomed out)_

Current close icons are ugly while max/min buttons are ok, so it's a really visible issue when you use something else than GNOME as a daily driver. Try with MATE in a virtual machine for example, you'll notice it immediatly. I have Xfce, same issue _(but sadly I can't use Materia with it because GTK2 panel support is inexistant, I'll switch when Xfce 4.13-14 will be available in my distro, it currently ships 4.12)_.

---

**EDIT:**

@$!# it seems that GitHub compresses image too much, I hope you see the difference.

If not, I've uploaded it [here](https://pix.toile-libre.org/upload/original/1559137965.png), should be better.

**Comment by nana-4** [comment]
Thanks for your suggestion!

I agree that the current close icon _for Metacity_ doesn't look good - it looks a bit too small. BUT this shape is based on Material Design, and is _rather_ consistent / geometrical. See:

- https://material.io/design/iconography/system-icons.html#system-icon-metrics (particularly "Stroke terminal")
- https://material.io/tools/icons/?icon=close&style=baseline (same shape, but different dimension)

So, I'd rather try to increase the dimension from 8x8 to 10x10 instead of adding corners at each end point :)

(FYI, currently only the close icon for Metacity has 8x8 dimension, while other close icons for gnome-shell/cinnamon/unity/xfwm have 10x10 dimension.)

Any objections?

**Comment by DarthWound** [comment]
Why not, maybe it'll be better _(8x8 to 10x10 for Metacity)_. I checked again and yeah Xfwm is not as bad as Metacity, still looks "blurry/pixelated" because of this missing end though, imho.

I agree that sticking to Material guidelines is globally the best thing to do, but as I think it'll never be possible to have a 1:1 Material experience _(limitations, beauty/consistency, etc.)_, personally I wouldn't mind a few exceptions. Plata has buttons like what I describe for example.

But I totally respect your decisions, and I usually fix/tweak themes to suit what I want, so I'll probably create my own Xfwm buttons :)

As always, keep up the good work. I can't wait for Xfce >=4.13 to use Materia again!

**Comment by nana-4** [comment]
Thanks for your comment :)

I've addressed this with the above commit.
