### ISSUE TITLE
[Feature request] Consistent window control button size/spacing (CSD/non-CSD)

### ISSUE THREAD

**Issue by m-thorsen** [nana-4/materia-theme#405]
Something that's irked me quite a bit in most GTK themes is the inconsistency of "control buttons" between CSD and non-CSD window. Fact is, we seem to be stuck using both. 

Windows, Macos and a few GTK themes (Arc for one?) compromise by always using the "legacy" button size and (in most cases) centering them vertically on CSDs. 

A little extra spacing could be added as to find the best middle ground.

This could also work well for "semi-styled" apps like Firefox (which uses legacy control buttons when CSD is enabled)

Current:
![image](https://user-images.githubusercontent.com/14907694/60266649-b94a4e00-98e8-11e9-891a-a0ba45c4c7ea.png)

Proposed (rough mockup): 
![image](https://user-images.githubusercontent.com/14907694/60266882-442b4880-98e9-11e9-897d-e4023d3b1d58.png)

**Comment by nana-4** [comment]
Thanks for the suggestion.

I think it's a complicated issue. Because having a _consistent_ window control button size between CSD and non-CSD means having _inconsistent_ button sizes inside a CSD headerbar. (normal headerbar buttons VS smaller window control buttons)

Personally I've never bothered that, but it's probably because I'm always showing only the close button (on GNOME). I guess, however, if we have all 3 window control buttons, it could be annoying.

So I tried to make the CSD window control buttons smaller _only when_ they are more than 2, but it was not achieved due to a technical problem (GTK3 lacking `:only-of-type` support :(). So, I suggest you either alternative solution:

1. Turn off the maximize button via settings. (Instead of the button, you still can maximize by double-clicking the title bar or by moving the window to the screen edge.) Possibly only 2 window control buttons could alleviate your trouble. I know some modern non-GTK (but CSD) apps have such a design/UI.

2. Control the size yourself by pasting the following code to `~/.config/gtk-3.0/gtk.css`:

```css
.titlebar button.titlebutton {
  min-height: 24px;
  min-width: 24px;
  padding: 0;
}
```

In any case, we won't fix this on the theme side, as GTK doesn't support `:only-of-type` or any other suitable style class. Sorry.
