### ISSUE TITLE
Gedit's header bar doesn't have shadows

### ISSUE THREAD

**Issue by johnfactotum** [nana-4/materia-theme#411]
**Reporter Info**

- Materia version: 20190315
- GTK3 version: 3.24.10
- Distribution (and version): Arch Linux
- Desktop environment (and version): GNOME 3.32
- Related application (and version): gedit 3.32.2

**Actual Issue**

Screenshot, with nautilus for comparison:
![image](https://user-images.githubusercontent.com/50942278/61344885-635f2b00-a842-11e9-8367-8545fecf443b.png)

Screenshot with tab bar:
![image](https://user-images.githubusercontent.com/50942278/61344660-8e954a80-a841-11e9-8540-66e069e30d50.png)

**Steps to Reproduce**

1. Open gedit
2. Observe that there's no shadow beneath the header bar
2. Open two or more tabs
3. Observe that there's still no shadow between the header bar and the tab bar.

**Comment by nana-4** [comment]
Thanks for the report.

Regarding the Gedit's headerbar shadows, it has already been fixed in the latest git master.

However in some other apps like 'GNOME Settings',  headerbars still don't have shadows even in git master. That's essentially due to an upstream bug, so we cannot fix it on the theme side,  unfortunately...
