### ISSUE TITLE
In Meld, banner no longer uses clored background

### ISSUE THREAD

**Issue by PJSingh5000** [nana-4/materia-theme#423]
**Reporter Info**
- Materia version: 1e77e0c0c67b9514bb08725d731d6959d2b19382
- GTK3 version: 3.24.8-1ubuntu1
- Distribution (and version): Ubuntu 19.04
- Desktop environment (and version): Gnome Shell
- Related application (and version): meld 3.20.0-2; also reference gedit 3.32.0-3 

**Actual Issue**
Meld no longer shows the banner above the text areas in color. There were three scenarios:
1. Loading
2. Matching
3. Error

Here are more details for each scenario:

1. The Loading banner usually happens for large remote files that take long to read into Meld. This banner was a shade of orange ("#FBBC05" ???) in previous versions of Materia.

2. The Matching banner is shown when two files match. This banner used to be a shade of green ("#34A853" ???) in previous versions of Materia.

3. The Error banner appears where there is some kind of error. (I think it was red in previous versions of Materia), but I have to try and recall how to invoke this banner in Meld. If I can remember, I'll add more info to this bug report.

**Steps to Reproduce**

1. Open Meld
2. Select File Comparison
3. Click Blank Comparison
4. Notice the "Files are identical" banner does not have a background color. I think it used to be some shade of green ("#34A853" ???).

**Additional Info**

Notice that the banner in Gedit (see below) behaves correctly in Materia. Meld should be the same as Gedit.

**Screen shots**

Meld with Materia, showing a white banner. This is the issue. It used to be green in previous versions of Materia.
![Screenshot from 2019-08-29 21-08-09](https://user-images.githubusercontent.com/19394936/63987489-76525580-caa6-11e9-90d3-5eccee9b9301.png)

Meld in Adwaita showing a blue banner. (Why blue and not green?... but that is out-of-scope here).
![Screenshot from 2019-08-29 21-12-50](https://user-images.githubusercontent.com/19394936/63987512-91bd6080-caa6-11e9-86d2-2835f4bc6684.png)

Gedit using Adwaita, showing colored banner for an error. It is blue, for Adwaita. (Why blue and not red or orange?... but that is out-of-scope here).
![Screenshot from 2019-08-29 21-18-33](https://user-images.githubusercontent.com/19394936/63987657-1c05c480-caa7-11e9-8cd3-db35aa390a67.png)

Gedit using Materia, showing colored banner for an error. It is orange. Meld with Materia theme also used to be like this for Loading large remote files.
![Screenshot from 2019-08-29 21-19-51](https://user-images.githubusercontent.com/19394936/63987695-3b9ced00-caa7-11e9-90f4-806ea6c332c4.png)

**Comment by nana-4** [comment]
Thanks for filing the issue.

It is an intentional change. The style is based on (relatively recently released) [Material banners guidelines](https://material.io/components/banners). However, it applies only to **info** or **question** message types, and remains colored for **warning** or **error** message types. That's why Meld's _info_ banner is white and Gedit's _warning_ banner remains orange.

Here is a summary before and after the changes:

Message type | Previous background color | Current background color
--- | --- | ---
info | green | no color (white)
question | blue | no color (white)
warning | orange | orange
error | red | red

Because I want to follow the Material Design Guidelines as much as possible in this theme, I'm not going to change the style for now 🙂
