### ISSUE TITLE
Keyboard Selection Visible Constantly

### ISSUE THREAD

**Issue by KUPOinyourWINDOW** [nana-4/materia-theme#424]
So within certain apps, most notable being nautilus they have the keyboard selection highlight activated without even pressing a key to trigger it, ruining the minimal look of the theme.

In the screenshot example, the highlight appears over "starred"

https://imgur.com/a/GGg5XJ7

**Comment by nana-4** [comment]
Thanks for the report.

Indeed it looks bad (even though in my environment it isn't highlighted without pressing keys). But unfortunately, there is no way to prevent it in GTK3 theme. (As far as I know, upcoming GTK4 will be able to prevent it, though.)

Since the current focus style is completely in line with the [Material Design guidelines](https://material.io/design/interaction/states.html#focus), I don't really want to change that. Therefore I'm going to close this as WONTFIX, sorry.

**Comment by nana-4** [comment]
Technically speaking:

This happened because we changed the focus style from `outline` to overlay (using `box-shadow`).

In GTK3, the CSS `outline` property is treated specially -- it's invisible even on focused widget, unless you press a key. On the other hand, other CSS properties are treated normally, so they are constantly visible on focused widget.

In upcoming GTK4, `outline` is treated as usual and `:focus(visible)` will be supported, so we should be able to solve this problem.
