### ISSUE TITLE
Invisible shell font color for dark version

### ISSUE THREAD

**Issue by kwingram25** [nana-4/materia-theme#446]
**Reporter Info**

- Materia version: 20190201-1ubuntu2
- GTK3 version: 3.24.12
- Distribution (and version): Ubuntu 19.10
- Desktop environment (and version): GNOME 3.34.1

**Actual Issue**

The default un-highlighted shell font for dark and dark-compact is invisible against the background

![Screenshot from 2019-11-17 12-08-37](https://user-images.githubusercontent.com/879755/69013396-2744ef80-0934-11ea-91fc-54afdf2281d0.png)

![Screenshot from 2019-11-17 12-18-47](https://user-images.githubusercontent.com/879755/69013430-74c15c80-0934-11ea-91dc-578c8458ba97.png)

**Comment by kaleidoc0de** [comment]
I had this issue the second I upgraded to eoan

```
 .popup-menu .popup-menu-item {
  color: rgba(255, 255, 255, 0.7);
}
```
adding the following css fixes most popup menus.
no fix for the calendar though

**Comment by nana-4** [comment]
Yes, it's because the Ubuntu package is too outdated and incompatible with GNOME 3.34, as written in the [README](https://github.com/nana-4/materia-theme#distro-packages):

> Note: Some distro packages (especially Ubuntu ones) may be outdated and incompatible with your desktop environment. You can check the latest version here.

I've already [reported](https://bugs.launchpad.net/ubuntu/+source/materia-gtk-theme/+bug/1846934) this problem to Ubuntu, but there is no update yet.

So please [manually install](https://github.com/nana-4/materia-theme#manual-installation) the newer version, or report to the Ubuntu packager.

**Comment by nana-4** [comment]
I added a warning for Ubuntu users in the README...
