### ISSUE TITLE
panel and title use the same color

### ISSUE THREAD

**Issue by Titubery** [nana-4/materia-theme#449]
How about using the same color of panel and window title？ It will look more integral with [GTK Title Bar](https://extensions.gnome.org/extension/1732/gtk-title-bar/) when maximizing window. More like a question than suggestion.Thanks:)
![image](https://user-images.githubusercontent.com/17917040/69133433-d6c6c100-0af0-11ea-8c17-1b8f7ee770d2.png)

**Comment by nana-4** [comment]
Thanks for the suggestion. 

In Material Design, top system bars usually always have a different shade of the app bars. See the [Material Design guidelines](https://material.io/design/color/applying-color-to-ui.html#top-bottom-app-bars) for details.

Since this is a Material Design theme, using the same color for panel and title bar is not what we want to do :)
