### ISSUE TITLE
KeepassXC broken

### ISSUE THREAD

**Issue by jtagcat** [nana-4/materia-theme#473]
With materia-dark-compact:
![image](https://user-images.githubusercontent.com/38327267/76951338-72cbd200-6903-11ea-8010-a1d87d8e8b35.png)
With adwaita-dark:
![image](https://user-images.githubusercontent.com/38327267/76951388-8414de80-6903-11ea-9094-fb949bc5e500.png)

**Reporter Info**

- Materia version: 20191017
- GTK3 version: 3.24.13
- Distribution (and version): Fedora 31
- Desktop environment (and version): GNOME Shell 3.34.4
- Related application (and version): KeepassXC

**Actual Issue**

**Steps to Reproduce**
1. Open KeepassXC with materia-dark* and a dark icon theme

**Additional Info**

Icon theme: Adwaita++-dark

**Comment by nana-4** [comment]
This happens because KeepassXC is a Qt app, not a GTK app.

As far as I know, Fedora Workstation only supports Adwaita or Adwaita-dark for Qt apps. If you specify any other theme (including Materia*), Qt apps are shown with Adwaita-Qt as a fallback.

Honestly, I'm not familiar with Qt theming and I don't know how to get around it. So, please, don't ask me for the workaround... :P

Anyway, this is not a Materia-specific bug and can't be fixed with this theme, so I'm going to close this issue.
