### ISSUE TITLE
Change login shell icon theme to current system set icon theme.

### ISSUE THREAD

**Issue by Nevuly** [nana-4/materia-theme#517]
I want to change my login shell icon theme to my current icon theme.

But I don't know how to change it in sass files.

Can you advise about that?

Thanks,
Nevuly.

**Comment by nana-4** [comment]
Sorry for the late reply.

I think you've installed your icon theme in `~/.icons` or `~/.local/share/icons`. Try moving your icon theme directory into `/usr/share/icons`.

**Comment by nana-4** [comment]
Anyway it is unrelated to this theme, I think :)

**Comment by Nevuly** [comment]
@nana-4 
I mean I want to change login shell status bar icon theme.

I tried to move icon to /usr/share/icons but It is not work.

**Comment by nana-4** [comment]
Did you restart your computer?

What display manager are you using? GDM? LightDM? Or anything else?

**Comment by Nevuly** [comment]
I using GNOME 3.36.x in arch linux.

**Comment by nana-4** [comment]
GNOME is a "desktop environment", not a "display manager"... Anyway I'll assume you're using GDM as your display manager (because it's GNOME's default display manager).

> login shell status bar icon theme

So you're talking about these icons, right?

![image](https://user-images.githubusercontent.com/9556384/88492613-e636cc00-cfe6-11ea-8722-cd95d09c8f0d.png)

If yes, again, it's unrelated to this theme. You need to install your icon theme under `/usr/share/icons` to load it within GDM.

If no, please provide more detailed information and follow [our issue template](https://github.com/nana-4/materia-theme/issues/new?assignees=&labels=question&template=question.md&title=) properly. Without enough information, I cannot help you...

**Comment by Nevuly** [comment]
@nana-4 Yeah, I using archlinux with GNOME 3.36.3 (plymouth-gdm).

And I using vimix icon theme and I installed it in /usr/share/icons.

But It not change that icons so, I think it is icon theme issue.

Can you advise about that? I don't know about how to work in gdm login shell.

**Comment by Nevuly** [comment]
And I have one more question. I want to change this theme effect color blue to grey, But I don't know how to change it.

I checked color change document and using oomox, I can't load it (maybe, it is my fault to load theme).

**Comment by nana-4** [comment]
> Can you advise about that? I don't know about how to work in gdm login shell.

In my environment (tested on Fedora 32 and rawhide), icons in GDM are properly changed when I change the icon theme via gnome-tweaks, so I have no idea what's wrong on your side. Sorry. But I guess this is a problem specific to your environment.

> I checked color change document and using oomox, I can't load it (maybe, it is my fault to load theme).

oomox outputs the theme with a unique name different from `Materia`. You can find and select the theme in gnome-tweaks.

Alternatively, you can replace all `#1a73e8` and `#8ab4f8` strings in this repository with your favorite color(s) and then rebuild the theme as follows: 

```
./render-assets.sh
sudo ninja install -C build
```
