### ISSUE TITLE
Change compact dark theme name to materia-compact-dark

### ISSUE THREAD

**Issue by pedrofleck** [nana-4/materia-theme#527]
Currently, some (non GTK) apps and websites have an auto switch to a dark theme when they see a "-dark" theme name. This doesn't work with Materia compact theme because it ends with "-compact".

Some examples: WhatsApp Web, DuckDuckGo and Telegram desktop.

PS: If you want to test it, you must use Epiphany or Firefox, Chrome(ium) is currently [broken](https://bugs.chromium.org/p/chromium/issues/detail?id=1091468).

**Comment by actionless** [comment]
> some (non GTK) apps and websites have an auto switch to a dark theme when they see a "-dark" theme name.

that completely wrong, you should report to those applications:

the correct way of detecting dark colorscheme is not parsing theme name, but getting GtkStyleContext and getting from it theme_bg_color and theme_fg_color, and measuring, which of values is darker

**Comment by nana-4** [comment]
> This doesn't work with Materia compact theme because it ends with "-compact".

Are you sure? Are those apps and websites working with **Adwaita** as you expected?

FYI, GTK apps normally use `gtk-application-prefer-dark-theme` which 
 reads `THEME_NAME/gtk-3.0/gtk-dark.css` instead of `THEME_NAME-dark/gtk-3.0/gtk.css`  to use theme's dark variant.

And I still didn't know how to reproduce it with those apps and websites... Can you clarify how to reproduce?

**Comment by nana-4** [comment]
Closing this as there is no reply from OP.
