### ISSUE TITLE
[Gnome Shell] Missing EventsSection style class

### ISSUE THREAD

**Issue by tuberry** [nana-4/materia-theme#537]
**Reporter Info**

- Materia version:  20200916
- GTK3 version: 3.24.23
- Distribution (and version): Arch Linux
- Desktop environment (and version): Gnome Shell 3.38
- Related application (and version): gnome-shell 
 
**Actual Issue**

Missing `event-*` style class of [EventsSection](https://gitlab.gnome.org/GNOME/gnome-shell/-/blob/master/js/ui/dateMenu.js#L91) in gnome-shell.css

![image](https://user-images.githubusercontent.com/17917040/96673050-33cd9580-1398-11eb-9422-be2fd699c588.png)

**Steps to Reproduce**

**Additional Info**

**Comment by nana-4** [comment]
My apologies for the late response.

This is odd, because the version `20200916` should have `event-*` style classes in `gnome-shell.css`. See: 475167920c12761600695497515ba025abfaa4ce

Can you still reproduce this bug? Please try reinstalling the theme and reopen this if you still have this problem. Thanks!
