### ISSUE TITLE
Is the separator among the workspace thumbnails of Gnome Shell overview purposefully designed?

### ISSUE THREAD

**Issue by tuberry** [nana-4/materia-theme#569]
**Questioner Info**

- Materia version: 20210322
- GTK3 version: 3.24.28
- Distribution (and version): Archlinux
- Desktop environment (and version): Gnome
- Related application (and version): Gnome Shell

**Description**
As per title,

![mat](https://user-images.githubusercontent.com/17917040/114035174-6cfbb280-98b1-11eb-92c1-c2104b647f7d.png)

In the Adwaita, there is a highlighted border instead. 

![adw](https://user-images.githubusercontent.com/17917040/114036273-83563e00-98b2-11eb-8225-06a3d3b27222.png)

I don't think the new design indicates the current workspace more clearly than the original.

Thanks!

**Comment by nana-4** [comment]
It seems you are using Materia gnome-shell theme for 3.38, not for 40. I'm assuming you installed/updated Materia **before** updating `gnome-shell` to 40.

By default our build system builds the gnome-shell theme based on your  _current_  `gnome-shell --version`. So when you update the major version of `gnome-shell`, you need to reinstall the theme. Otherwise the gnome-shell theme remains for the previous version.

And the Arch package maintainers should've bump the `materia-gtk-theme` version e.g. to `20210322-2`, with the build option `-Dgnome_shell_version=40`, when their `gnome-shell` package was updated to `40.0`. Then this wasn't happening. Someone needs to tell this to the Arch package maintainers...

**Comment by tuberry** [comment]
Thanks, I see it might be the same reason for #541 and #537. I've reported [it](https://bugs.archlinux.org/task/70377). I think the Arch devs should divide the theme into two packages `materia-gtk-theme` and `materia-shell-theme` in a package group `materia-theme`.  Is this possible?

**Comment by nana-4** [comment]
Thanks for reporting it!

In `INSTALL.md`, I've added a note about it for package maintainers.

I think there is nothing left to do for this on our side, so I'm going to close this.

Thanks again for your contribution :)
