### ISSUE TITLE
Icon theme icons instead of assets 

### ISSUE THREAD

**Issue by rudrab** [nana-4/materia-theme#578]
Dear dev,
I am using materia-theme for years. I have also modified the colour (when you shifted from blue black to more Adwaita like colour scheme. I don't remember the version).

One thing I don't like is the assets images. I am sure there is a solid reason why you use assets, but I want to use icons from icon themes when available. Like `no-notifications.svg` should be aliased to `current_icon_theme/scalable/status/notifications-symbolic.svg` etc. 

In `gnome-shell/gresource.xml`, file names are hardcoded, using `<file>icons from assets</file>`.  At present, I am copying icons from my preferred icon theme([dual](https://github.com/rudrab/dual) that I have created) to `assets_dark` to get the preferred look. 

Is it possible to change `gresources.xml`  so that it accepts the current theme icon?

**Comment by nana-4** [comment]
> Is it possible to change gresources.xml so that it accepts the current theme icon?

Unfortunately, no, it's not possible so far. As you expected, there are solid reasons why we _have to_ use assets instead of icons from icon themes. For example, the path of `no-notifications.svg` is [hard-coded](https://gitlab.gnome.org/GNOME/gnome-shell/-/blob/master/js/ui/calendar.js#L892) in the upstream JS code.

If you really want to use icons from icon themes, you need to request it upstream. It's not fixable on the theme side, unfortunately.

**Comment by rudrab** [comment]
@nana-4 : Thanks for explaining.
